# Generated by Django 3.2.3 on 2023-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
