# Generated by Django 3.2.3 on 2023-12-09 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('editor', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='LibroCategoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='categories.categoria')),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='books.libro')),
            ],
            options={
                'db_table': 'libros_categorias',
            },
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, to='authors.autor')),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='books.libro')),
            ],
            options={
                'db_table': 'libros_autores',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', through='books.LibroAutor', to='authors.Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='categorias',
            field=models.ManyToManyField(related_name='libros', through='books.LibroCategoria', to='categories.Categoria'),
        ),
    ]
