# Generated by Django 3.2.3 on 2023-12-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('editor', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LibroCategoria',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, to='books.categoria')),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='books.libro')),
            ],
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, to='books.autor')),
                ('libro', models.ForeignKey(db_column='libro_id', on_delete=django.db.models.deletion.CASCADE, to='books.libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', through='books.LibroAutor', to='books.Autor'),
        ),
        migrations.AddField(
            model_name='libro',
            name='categorias',
            field=models.ManyToManyField(related_name='libros', through='books.LibroCategoria', to='books.Categoria'),
        ),
    ]
