# Generated by Django 3.2.3 on 2023-12-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('autores', models.CharField(max_length=255)),
                ('categorias', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('editor', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=255, null=True)),
                ('fuente', models.CharField(max_length=255)),
                ('google_id', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'libros',
            },
        ),
    ]
