# Generated by Django 3.2.3 on 2023-12-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autores',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='libro',
            table='libros',
        ),
        migrations.AlterModelTable(
            name='libroautor',
            table='libros_autores',
        ),
        migrations.AlterModelTable(
            name='librocategoria',
            table='libros_categorias',
        ),
    ]
